### ISSUE TITLE
[Bug]: Falta softdelete en el modelo Payment

### ISSUE THREAD

**Issue by neurotools** [elmudometal/payment-gateways#15]
### What happened?

En la migración la tabla payments tiene softdeletes, pero el modelo no usa el trait softdelete.

### How to reproduce the bug

Da error al usar el filtro "Tables\Filters\TrashedFilter::make()" en Filament.

### Package Version

0.1.9-beta

### PHP Version

8.3

### Laravel Version

11.x

### Which operating systems does with happen with?

macOS

**Comment by elmudometal** [comment]
bug corregido con pr #16
